"""Render extras — figures kept callable but outside the thesis figure list.

These plots informed methodology decisions but were cut from the thesis
itself. The underlying analyses (in `analysis_scratch/`) remain valid;
running this file regenerates the figures whenever you want to revisit
them. Sister to `main_save_figures.py` / `main_save_tables.py`.

Pre-condition: `main_save_figures.py` must be run/imported once in this
session BEFORE this file, so `output/.figure_captions.json` exists. The
caption strings for these figures still live in main_save_figures.py's
FIGURE_CAPTIONS dict — the policy is "captions stay where they live"; if
that becomes annoying, migrate them to a TABLE_CAPTIONS-style local dict
later (same pattern as main_save_tables.py).
"""

import os
import sys
import warnings
from pathlib import Path

BASE = (Path(__file__).resolve().parent
        if "__file__" in globals() else Path.cwd())
os.chdir(BASE)
sys.path.insert(0, str(BASE))
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

from wavescripts.improved_data_loader import load_analysis_data, ANALYSIS_PROBES
from wavescripts.plotter import plot_sound_speed, plot_td_vs_fft
from wavescripts.save_utils import _run_delegated_if_missing

# ══════════════════════════════════════════════════════════════════════════════
# Light data load — combined_meta only (no processed_dfs needed for these 5).
# Folder list mirrors main_save_figures.py:ALL_PROCESSED_DIRS via glob.
# ══════════════════════════════════════════════════════════════════════════════
ALL_PROCESSED_DIRS = sorted(BASE.glob("waveprocessed/PROCESSED-*"))
combined_meta, _, _, _ = load_analysis_data(*ALL_PROCESSED_DIRS,
                                            load_processed=False)

# %%
# [DATA: META]  — ch04_sound_speed
"""
── CH04 § 3d — Speed-of-sound / lab temperature drift ───────────────────────
Goal: show that lab temperature variation introduces < 0.4 % amplitude scale
error, and that this cancels exactly for OUT/IN ratios.
Data: sound_speed_mean_ms / sound_speed_std_ms in combined_meta (pipeline).
"""

_pv_sound_speed = {
    "filters": {},
    "plotting": {
        "show_plot":   True,
        "save_plot":   True,
        "draft":       False,
        "figure_name": "ch04_sound_speed",
        "force_stub":  True,
        "figsize":     (10, 3),
    },
}

plot_sound_speed(combined_meta, _pv_sound_speed, chapter="04")

# %%
# [DATA: META]  — ch04_td_vs_fft + ch04_td_vs_fft_scatter
"""
── CH04 § 4-5 — Time-domain vs FFT amplitude: why A_FFT is required ─────────
Goal: demonstrate that time-domain amplitude is wind-dominated at the IN probe
under full wind, making OUT/IN from A_td meaningless. FFT amplitude isolates
the paddle frequency and is unaffected by broadband wind energy.
Data: combined_meta wave rows (Probe {pos} Amplitude and Probe {pos} Amplitude (FFT)).
"""

_pv_td_vs_fft = {
    "filters": {
        "min_periods":               10,
        "WaveAmplitudeInput [Volt]": None,
        "WaveFrequencyInput [Hz]":   None,
        "WindCondition":             None,
        "PanelCondition":            None,
    },
    "plotting": {
        "show_plot":   True,
        "save_plot":   True,
        "draft":       True,
        "figure_name": "ch04_td_vs_fft",
        "force_stub":  True,
        "probes":      ANALYSIS_PROBES,
    },
}

plot_td_vs_fft(combined_meta, _pv_td_vs_fft, chapter="04")

_pv_td_vs_fft_scatter = {
    "filters": {**_pv_td_vs_fft["filters"]},
    "plotting": {
        **_pv_td_vs_fft["plotting"],
        "scatter":     True,
        "figure_name": "ch04_td_vs_fft_scatter",
    },
}
plot_td_vs_fft(combined_meta, _pv_td_vs_fft_scatter, chapter="04")

# %%
# [DATA: DELEG]  — analysis_scratch/sw_correction.py
"""
── CH04 § 4d — Standing-wave correction test (negative evidence) ────────────
Goal: show that applying a standing-wave correction at R = 0.20 to the raw
OUT/IN(FFT) curve creates a violent zigzag not present in the raw data.
This is the complementary result to §4c — raw data shows no node/antinode
fingerprint at the predicted frequency spacing, putting an upper bound of
R ≲ 0.05 on the panel reflection coefficient.

Generated by analysis_scratch/sw_correction.py. Writes figure + stub
directly to output/. Re-run after any pipeline change that alters OUT/IN.
"""

_run_delegated_if_missing(
    "analysis_scratch/sw_correction.py",
    [Path("output/FIGURES/ch04_sw_correction_test.pdf"),
     Path("output/TEXFIGU/ch04_sw_correction_test.tex")],
    label="ch04_sw_correction_test",
)

# %%
# [DATA: DELEG]  — analysis_scratch/sliding_afft_fullwind_sweep.py
"""
── CH04 § 4e — Sliding-window FFT stability at the IN probe ─────────────────
Goal: show that the paddle-frequency FFT amplitude at the IN probe
(9373/170) is stable across the run for fullwind per240 conditions. Any
apparent discrepancies between the pipeline AFFT (short analysis window)
and alternative FFT windows reflect FFT bin-grid alignment (see §4b),
not physical within-run transients. This is a companion figure to §4b —
§4b establishes the bias mechanism and OUT/IN cancellation; §4e shows
that the underlying signal is genuinely stable (so the bias is the only
suspect when short/long-window FFT values disagree).

Generated by analysis_scratch/sliding_afft_fullwind_sweep.py. Writes
PDF + stub directly into output/. A deeper 1.5 Hz / 0.2 V zoom lives
in analysis_scratch/sliding_afft_15hz_02v_zoom.{py,pdf} for reference.
"""

_run_delegated_if_missing(
    "analysis_scratch/sliding_afft_fullwind_sweep.py",
    [Path("output/FIGURES/ch04_sliding_afft_stability.pdf"),
     Path("output/TEXFIGU/ch04_sliding_afft_stability.tex")],
    label="ch04_sliding_afft_stability",
)

# %%
# [DATA: DELEG]  — analysis_scratch/window_choice_figure.py
"""
── CH04 § 4o — Window-choice visual: Option B vs nowind eyeball + fullwind empirical ──
Geometry-only figure (no per-run data) showing the post-squeeze Option B
window per (f, probe) overlaid against:

  • upper grey-hash band  → nowind plateau bounds eyeballed in
                            RampDetectionBrowser (snarvei_eyeballing.md, 0.2 V)
  • lower red-hash band   → fullwind empirical plateau (per40 sliding A_FFT,
                            ±2 % relaxed criterion, n=1 per cell) from
                            per40_plateau_end_aggregated.csv

Option B parameters: t_start = r/c_g(f, h) + 10/f, length N(f)/f, with
N(f) = {1.3:10, 1.4:13, 1.5:13, 1.6:13}. Markers t_arr (▼ blue),
t_paras (▽ red), per40 paddle stop (✕ purple) for orientation.

Visual claim: the Option B window sits inside both nowind and fullwind
plateau bounds at every (f, probe) cell, except (1.3 Hz IN fullwind) where
the empirical plateau ends ~2 s before the window does — that cell is
also bound by the parasitic 2f arrival and is the binding case.

Outputs:
    output/FIGURES/ch04_window_choice.pdf
    output/TEXFIGU/ch04_window_choice.tex
"""

_run_delegated_if_missing(
    "analysis_scratch/window_choice_figure.py",
    [Path("output/FIGURES/ch04_window_choice.pdf"),
     Path("output/TEXFIGU/ch04_window_choice.tex")],
    label="ch04_window_choice",
)
