# %%
"""
Overlay our fig5 wind profile on top of the Vollestad & Jensen (2021) reference
figure, with their axes rectangles pixel-aligned.

Pipeline:
1. Find the most recent `windprofile_combined_conditions_log_flipped_*.pdf`
   in windresults/ (generated by windprofile_combined.py fig5).
2. Rasterise both PDFs via `sips` (macOS).
3. Detect each axes rectangle by scanning for "thick" (≥3-row) dark lines.
   This skips 1-pixel PDF-crop-edge artifacts that trip naive detectors.
4. Resize ours so the axes WIDTHS match.
5. Composite with axes top-left corners aligned; ink is tinted red (ours) and
   blue (Vollestad) before blending so both can be seen.
6. Save to `windresults/vollestad_comparison_overlay.png`.

Why not do this in `windprofile_combined.py`? The overlay depends on rasterising
the saved PDF *after* it's been written, so it's a post-processing step on an
output artifact. Keeping it in its own script also means it can be re-run
against any prior fig5 PDF without re-running the whole profile pipeline.
"""
import subprocess
import glob
import os
from pathlib import Path
from PIL import Image
import numpy as np


WIND_RESULTS = Path(os.path.expanduser("~/Kodevik/wave_project/windresults"))
REF = Path(os.path.expanduser(
    "~/Kodevik/wave_project/windscripts/vollestad-vindprofile_cropped copy.pdf"
))
OUT_PNG = WIND_RESULTS / "vollestad_comparison_overlay.png"


def latest_fig5():
    matches = sorted(glob.glob(str(
        WIND_RESULTS / "windprofile_combined_conditions_log_flipped_*.pdf"
    )))
    if not matches:
        raise FileNotFoundError(
            "No windprofile_combined_conditions_log_flipped_*.pdf in windresults/. "
            "Run windprofile_combined.py first."
        )
    return Path(matches[-1])


def pdf_to_png(pdf_path, out_path, max_dim=1500):
    subprocess.run(
        ["sips", "-s", "format", "png", "-Z", str(max_dim),
         str(pdf_path), "--out", str(out_path)],
        check=True, capture_output=True,
    )


def axes_bbox(png_path):
    """Detect the 4 spines of the axes rectangle.

    A true spine is a rendered line ≥3 px thick (due to anti-aliasing). Rows or
    columns where only a single isolated dark line exists (PDF crop-edge
    artifact) are ignored by requiring neighbouring rows/cols to also carry ink.
    """
    img = np.asarray(Image.open(png_path).convert("L"), dtype=np.uint8)
    dark = img < 180
    row_frac = dark.mean(axis=1)
    col_frac = dark.mean(axis=0)

    def thick(frac, hi=0.4, lo=0.15):
        ok = np.zeros_like(frac, dtype=bool)
        ok[1:-1] = (frac[1:-1] > hi) & (frac[:-2] > lo) & (frac[2:] > lo)
        return np.where(ok)[0]

    rows = thick(row_frac)
    cols = thick(col_frac)
    return dict(
        lef=int(cols[0]), rig=int(cols[-1]),
        top=int(rows[0]), bot=int(rows[-1]),
        width=int(cols[-1] - cols[0]),
        height=int(rows[-1] - rows[0]),
    )


def stamp(canvas, img_pil, color_rgb, box, anchor):
    """Place img_pil onto canvas so its axes-box top-left lands at `anchor`.

    Non-white pixels are tinted by `color_rgb` proportional to their darkness,
    then multiplicatively blended into the canvas so overlapping inks darken.
    """
    arr = np.asarray(img_pil.convert("RGBA"), dtype=np.float32)
    rgb = arr[..., :3]
    lum = rgb.mean(axis=2) / 255.0
    ink = np.clip(1.0 - lum, 0.0, 1.0)[..., None]
    tinted = np.array(color_rgb, dtype=np.float32) * ink + 255.0 * (1.0 - ink)

    ih, iw = arr.shape[:2]
    x0 = anchor[0] - box["lef"]
    y0 = anchor[1] - box["top"]
    cx0 = max(0, x0); cy0 = max(0, y0)
    cx1 = min(canvas.shape[1], x0 + iw); cy1 = min(canvas.shape[0], y0 + ih)
    ix0 = cx0 - x0; iy0 = cy0 - y0
    ix1 = ix0 + (cx1 - cx0); iy1 = iy0 + (cy1 - cy0)

    patch   = canvas[cy0:cy1, cx0:cx1, :] / 255.0
    tint01  = tinted[iy0:iy1, ix0:ix1, :] / 255.0
    canvas[cy0:cy1, cx0:cx1, :] = patch * tint01 * 255.0
    return canvas


# %%
def main():
    mine_pdf = latest_fig5()
    print(f"Using our fig5:  {mine_pdf.name}")
    print(f"Reference:       {REF.name}")

    tmp_mine = Path("/tmp") / "vollestad_overlay_mine.png"
    tmp_ref  = Path("/tmp") / "vollestad_overlay_ref.png"
    pdf_to_png(mine_pdf, tmp_mine)
    pdf_to_png(REF,      tmp_ref)

    mine = Image.open(tmp_mine).convert("RGBA")
    ref  = Image.open(tmp_ref).convert("RGBA")

    mine_box = axes_bbox(tmp_mine)
    ref_box  = axes_bbox(tmp_ref)
    print(f"  ours axes: {mine_box['width']}×{mine_box['height']} px")
    print(f"  ref  axes: {ref_box['width']}×{ref_box['height']} px")

    # Rescale ours so axes WIDTHS match.
    scale = ref_box["width"] / mine_box["width"]
    new_size = (int(mine.size[0] * scale), int(mine.size[1] * scale))
    mine_rs = mine.resize(new_size, Image.LANCZOS)
    tmp_mine_rs = Path("/tmp") / "vollestad_overlay_mine_rs.png"
    mine_rs.save(tmp_mine_rs)
    mine_box_rs = axes_bbox(tmp_mine_rs)
    print(f"  ours rescaled axes: {mine_box_rs['width']}×{mine_box_rs['height']} px")

    W = max(ref.size[0], mine_rs.size[0]) + 100
    H = max(ref.size[1], mine_rs.size[1]) + 100
    canvas = np.ones((H, W, 3), dtype=np.float32) * 255
    anchor = (50, 50)
    canvas = stamp(canvas, ref,     (30, 80, 200),  ref_box,    anchor)  # blue
    canvas = stamp(canvas, mine_rs, (210, 40, 40),  mine_box_rs, anchor)  # red

    Image.fromarray(np.clip(canvas, 0, 255).astype(np.uint8)).save(OUT_PNG)
    print(f"\nSaved: {OUT_PNG}")
    return OUT_PNG


if __name__ == "__main__":
    main()
# %%
