"""
H&G window fitness check — proposed-formula window overlaid on η(t)
====================================================================

For each thesis frequency (1.3, 1.4, 1.5, 1.6 Hz at 0.2 V), one figure
showing four representative runs — (per40 nowind, per40 fullwind,
per240 nowind, per240 fullwind) — at the IN probe (9373/170) and the
OUT probe (12400/250). The shaded green band is the H&G window from
the proposed formula:

    t_start = r / c_g(f, h) + N_OFFSET / f       (seconds)
    t_end   = t_start + 10 / f                   (10T length)

with N_OFFSET = 15 periods (= ~5 wavemaker-ramp + 10 H&G safety).
Start is snapped to the nearest zero-upcrossing within ±T (same as
the live pipeline). End = start + 10·samples_per_period (no separate
end-snap in this prototype — kept simple).

Visual purpose: confirm the window sits inside the wavetrain at every
thesis frequency for both per40 (paddle stops at 40/f s) and per240
(plenty of paddle-driven signal). x-axis matched at 0–50 s and y-axis
shared across all 8 panes so the cells stack on the same time + amplitude
scale.

Outputs (4 thesis figures + scratch mirrors):
    output/FIGURES/ch04_hg_per40_window_fitness_f13.{pdf}
    output/FIGURES/ch04_hg_per40_window_fitness_f14.{pdf}
    output/FIGURES/ch04_hg_per40_window_fitness_f15.{pdf}
    output/FIGURES/ch04_hg_per40_window_fitness_f16.{pdf}
    output/TEXFIGU/ch04_hg_per40_window_fitness_f{13,14,15,16}.tex
    analysis_scratch/hg_per40_window_fitness_f{13,14,15,16}.{pdf,png}

Run from repo root:
    /opt/anaconda3/envs/draumkvedet/bin/python analysis_scratch/hg_per40_window_fitness.py
"""

import sys
import warnings
from pathlib import Path

warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

BASE = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE))

import os
os.chdir(BASE)

from wavescripts.improved_data_loader import load_analysis_data, load_processed_dfs
from wavescripts.plot_utils import apply_thesis_style, WIND_COLOR_MAP, amp_to_label
from wavescripts.constants import c_group, HG
import wavescripts.plot_utils as pu

apply_thesis_style()

# ── Config ──────────────────────────────────────────────────────────────
FS              = 250.0
TARGET_FREQS    = [1.3, 1.4, 1.5, 1.6]
TARGET_AMP      = 0.2
PER240_THRESHOLD_T = 50

PROBES = ["9373/170", "12400/250"]
PROBE_LABEL = {"9373/170": "IN  (9373/170)", "12400/250": "OUT (12400/250)"}
PROBE_R_M   = {"9373/170": 9.373, "9373/340": 9.373, "12400/250": 12.400}

# === Proposed H&G formula (CH04 §4o) ====================================
# Replaces the original [50T, 60T]+probe-shift rule. Justified at all four
# thesis frequencies in the figures generated by this script — the snapped
# window lands firmly inside the eyeballed plateau at IN+OUT, per40+per240.
N_OFFSET_PERIODS = 15.0    # 5 (wavemaker ramp) + 10 (H&G "10 periods after arrival")
WINDOW_PERIODS   = 10.0    # H&G's 10T window
SNAP_HALFWIDTH_T = 1.0     # ±1 wave period UC search window for snap-to-start
TANK_DEPTH_M     = HG.TANK_DEPTH_M

# Matched x-axis for ALL rows (per40 and per240) so the reader compares them
# on the same time scale.
X_MAX_S = 48.0

# Canon — march-2026 cond4 lowrange
PROCESSED_DIRS = [
    Path("waveprocessed/PROCESSED-20260326-ProbePos4_31_FPV_2-tett6roof-under9Mooring-height100-lowrange"),
    Path("waveprocessed/PROCESSED-20260327-ProbePos4_31_FPV_2-tett6roof-under9Mooring30-height100-lowrange"),
]

SCRATCH_DIR  = Path(__file__).parent
THESIS_FIGS  = BASE / "output" / "FIGURES"
THESIS_STUBS = BASE / "output" / "TEXFIGU"
THESIS_FIGS.mkdir(parents=True, exist_ok=True)
THESIS_STUBS.mkdir(parents=True, exist_ok=True)


# ── Helpers ─────────────────────────────────────────────────────────────
def proposed_window_theoretical(probe: str, f_paddle: float):
    """t_start, t_end (seconds) per the proposed formula, pre-snap."""
    r_m = PROBE_R_M[probe]
    c_g = c_group(f_paddle, TANK_DEPTH_M)
    t_start = r_m / c_g + N_OFFSET_PERIODS / f_paddle
    t_end   = t_start + WINDOW_PERIODS / f_paddle
    return t_start, t_end


def snap_to_upcrossing(signal: np.ndarray, target_idx: int,
                       f_paddle: float, fs: float = FS) -> int:
    """Snap target sample idx to nearest zero-upcrossing of `signal` within
    ±SNAP_HALFWIDTH_T periods. Local DC mean of first 2 s as threshold —
    matches the live pipeline. Returns target_idx if no UC found in window.
    """
    if target_idx < 0 or target_idx >= len(signal):
        return target_idx
    samples_per_period = int(round(fs / f_paddle))
    halfwidth = int(round(SNAP_HALFWIDTH_T * samples_per_period))

    baseline_n = int(2 * fs)
    upcross_level = float(np.nanmean(signal[:baseline_n]))
    above = signal > upcross_level
    all_uc = np.where((~above[:-1]) & above[1:])[0] + 1

    lo = max(0, target_idx - halfwidth)
    hi = min(len(signal) - 1, target_idx + halfwidth)
    cands = all_uc[(all_uc >= lo) & (all_uc <= hi)]
    if len(cands) == 0:
        return target_idx
    return int(cands[np.argmin(np.abs(cands - target_idx))])


def proposed_window_snapped(signal: np.ndarray, probe: str,
                            f_paddle: float, fs: float = FS):
    """(t_start_s, t_end_s) using the proposed formula, with start snapped
    to the nearest UC within ±T. End = start + 10·samples_per_period."""
    t_th_start, _ = proposed_window_theoretical(probe, f_paddle)
    target_start_idx = int(round(t_th_start * fs))
    snap_start_idx = snap_to_upcrossing(signal, target_start_idx, f_paddle, fs)
    samples_per_period = int(round(fs / f_paddle))
    snap_end_idx = snap_start_idx + int(round(WINDOW_PERIODS * samples_per_period))
    return snap_start_idx / fs, snap_end_idx / fs


# ── Load ────────────────────────────────────────────────────────────────
print("1. Loading meta + processed_dfs (canon March-2026 lowrange) …")
combined_meta, _, _, _ = load_analysis_data(*PROCESSED_DIRS, load_processed=False)
processed_dfs = load_processed_dfs(*PROCESSED_DIRS)
print(f"   meta: {len(combined_meta)} rows · processed_dfs: {len(processed_dfs)} runs")


def _safe_get_amp(s):
    return pd.to_numeric(s, errors="coerce")


def select_canon(target_freq: float) -> pd.DataFrame:
    mask = (
        np.isclose(_safe_get_amp(combined_meta["WaveFrequencyInput [Hz]"]),
                   target_freq, atol=0.02)
        & np.isclose(_safe_get_amp(combined_meta["WaveAmplitudeInput [Volt]"]),
                     TARGET_AMP, atol=0.01)
        & (combined_meta["PanelCondition"] == "full")
        & (combined_meta["quality_flag"] == "ok")
    )
    sub = combined_meta[mask].copy()
    sub["N_input_periods"] = pd.to_numeric(sub["WavePeriodInput"], errors="coerce")
    sub["run_type"] = np.where(sub["N_input_periods"] >= PER240_THRESHOLD_T,
                               "per240", "per40")
    return sub


def pick_run(scope: pd.DataFrame, run_type: str, wind: str):
    s = scope[(scope["run_type"] == run_type) & (scope["WindCondition"] == wind)]
    if s.empty:
        return None
    # Prefer runs with all probe eta signals available — rare to miss but
    # be safe.
    for _, r in s.iterrows():
        df = processed_dfs.get(r["path"])
        if df is None:
            continue
        if all(f"eta_{p}" in df.columns or f"eta_{p}_interp" in df.columns
               for p in PROBES):
            return r
    return s.iloc[0]


def _eta(df: pd.DataFrame, pos: str):
    for col in (f"eta_{pos}_interp", f"eta_{pos}"):
        if col in df.columns:
            return df[col].to_numpy(dtype=float)
    return None


# ── Per-frequency figure builder ────────────────────────────────────────
def build_figure_for(target_freq: float):
    sel = select_canon(target_freq)
    print(f"\n— f={target_freq:.2f} Hz: {len(sel)} canonical runs "
          f"(per40 n={int((sel['run_type']=='per40').sum())}, "
          f"per240 n={int((sel['run_type']=='per240').sum())})")

    cells = [(rt, w) for rt in ("per40", "per240") for w in ("no", "full")]
    picks = {(rt, w): pick_run(sel, rt, w) for rt, w in cells}
    for (rt, w), r in picks.items():
        if r is None:
            print(f"   WARN no run for ({rt}, {w}) at {target_freq:.2f} Hz")
        else:
            print(f"   ({rt}, {w}) → {Path(str(r['path'])).name}")

    # Pre-print theoretical (pre-snap) window for reference
    th_in_s,  th_in_e  = proposed_window_theoretical("9373/170",  target_freq)
    th_out_s, th_out_e = proposed_window_theoretical("12400/250", target_freq)
    print(f"   PROPOSED  IN  (theoretical): [{th_in_s:5.2f}, {th_in_e:5.2f}] s")
    print(f"   PROPOSED  OUT (theoretical): [{th_out_s:5.2f}, {th_out_e:5.2f}] s")

    fig, axes = plt.subplots(4, 2, figsize=(6.2, 8.5), sharex=True, sharey=True)

    row_order = [
        ("per40",  "no"),
        ("per40",  "full"),
        ("per240", "no"),
        ("per240", "full"),
    ]

    for row_i, (rt, wind) in enumerate(row_order):
        run = picks.get((rt, wind))
        color = WIND_COLOR_MAP[wind]
        n_periods = float(run["N_input_periods"]) if run is not None else np.nan
        f_paddle  = (float(run["WaveFrequencyInput [Hz]"])
                     if run is not None else target_freq)
        t_paddle_stop = (n_periods / f_paddle
                         if np.isfinite(n_periods) else np.nan)

        for col_i, probe in enumerate(PROBES):
            ax = axes[row_i, col_i]
            if run is None:
                ax.text(0.5, 0.5, "no run", ha="center", va="center",
                        transform=ax.transAxes, color="gray")
                ax.set_xticks([]); ax.set_yticks([])
                continue

            df = processed_dfs.get(run["path"])
            sig = _eta(df, probe) if df is not None else None
            if sig is None:
                ax.text(0.5, 0.5, f"no eta for {probe}", ha="center", va="center",
                        transform=ax.transAxes, color="gray", fontsize=8)
                continue

            t = np.arange(len(sig)) / FS
            m = t <= X_MAX_S
            ax.plot(t[m], sig[m], color=color, lw=0.45, alpha=0.85)

            # === Proposed-formula window, snapped per run on this probe's signal
            t_gs, t_ge = proposed_window_snapped(sig, probe, target_freq, FS)
            ax.axvspan(t_gs, t_ge, color="#2ECC71", alpha=0.22, lw=0,
                       label="proposed H&G window (N=15 + UC-snap)")
            ax.axvline(t_gs, color="#2ECC71", lw=0.6, ls="--", alpha=0.7)
            ax.axvline(t_ge, color="#2ECC71", lw=0.6, ls="--", alpha=0.7)
            ax.text(0.5 * (t_gs + t_ge), 0.92,
                    f"[{t_gs:.1f}, {t_ge:.1f}] s",
                    transform=ax.get_xaxis_transform(),
                    ha="center", va="top", fontsize=7,
                    color="#1A6E2A", alpha=0.85)

            # Paddle stop (per40 only — per240 stop is past X_MAX_S)
            if np.isfinite(t_paddle_stop) and t_paddle_stop <= X_MAX_S:
                ax.axvline(t_paddle_stop, color="#7F3FBF", lw=1.0, ls=":")
                ax.text(t_paddle_stop + 0.3, 0.05,
                        f"paddle stop ({t_paddle_stop:.1f} s)",
                        transform=ax.get_xaxis_transform(), fontsize=7,
                        color="#7F3FBF", va="bottom", ha="left")

            ax.set_xlim(0, X_MAX_S)
            ax.grid(True, alpha=0.25, lw=0.4)
            ax.tick_params(labelsize=8)
            # All identifying text (y-axis label, row tag, probe tag) lives
            # in the .tex stub's caption — figure shows numeric ticks only.
            if row_i == 3:
                ax.set_xlabel("time from wavemaker start [s]", fontsize=8)

    # fig.suptitle( #wasting space
    #     f"$f$ = {target_freq:.1f} Hz · {amp_to_label(TARGET_AMP)}"
    #     " (identical paddle drive in all 8 panes)",
    #     fontsize=10, y=0.995,
    # )
    fig.tight_layout(rect=[0, 0, 1, 0.97])
    fig.subplots_adjust(wspace=0.05)

    f_tag = f"f{int(round(target_freq * 10))}"
    figure_name = f"ch04_hg_per40_window_fitness_{f_tag}"

    scratch_pdf = SCRATCH_DIR / f"hg_per40_window_fitness_{f_tag}.pdf"
    scratch_png = SCRATCH_DIR / f"hg_per40_window_fitness_{f_tag}.png"
    thesis_pdf  = THESIS_FIGS / f"{figure_name}.pdf"
    # thesis_pgf  = THESIS_FIGS / f"{figure_name}.pgf"

    fig.savefig(scratch_pdf, bbox_inches="tight")
    fig.savefig(scratch_png, dpi=130, bbox_inches="tight")
    fig.savefig(thesis_pdf,  bbox_inches="tight")
    # try: % we don't really need PGF anymore
    #     fig.savefig(thesis_pgf, bbox_inches="tight")
    # except Exception:
    #     # PGF backend can fail on some matplotlib installs — non-fatal.
    #     pass
    plt.close(fig)
    print(f"   scratch → {scratch_pdf.relative_to(BASE)}")
    print(f"   thesis  → {thesis_pdf.relative_to(BASE)}")

    # ── TEXFIGU stub via shared helper ───────────────────────────────────
    pu.ACTIVE_DATASETS = [p.name for p in PROCESSED_DIRS]
    pu.TEXFIGU_DIR = THESIS_STUBS
    pu.FIGURES_DIR = THESIS_FIGS

    n_per40  = int((sel["run_type"] == "per40").sum())
    n_per240 = int((sel["run_type"] == "per240").sum())

    _meta_stub = pu.build_fig_meta(
        {
            "filters": {
                "PanelCondition":            "full",
                "WaveFrequencyInput [Hz]":   target_freq,
                "WaveAmplitudeInput [Volt]": TARGET_AMP,
                "WindCondition":             ["no", "full"],
                "quality_flag":              "ok",
                "probes":                    "IN=9373/170, OUT=12400/250",
            },
            "plotting": {"figure_name": figure_name},
        },
        chapter="04",
        data_df=sel,
        extra={"script": "analysis_scratch/hg_per40_window_fitness.py"},
        computed_in=(
            "analysis_scratch/hg_per40_window_fitness.py "
            "(proposed H&G formula: t_start = r/c_g(f,h) + 15/f, length 10T, "
            "start snapped to nearest upcrossing within ±T)"
        ),
        data_class="DFS",
        grouper="one representative run per (run_type × wind) cell",
        collapse_panels=False,
        extra_params=(
            f"f_paddle = {target_freq} Hz; "
            f"N_offset = {int(N_OFFSET_PERIODS)} periods; "
            f"window length = {int(WINDOW_PERIODS)} T; "
            f"r_IN = {PROBE_R_M['9373/170']} m, r_OUT = {PROBE_R_M['12400/250']} m; "
            f"depth = {TANK_DEPTH_M} m"
        ),
        extra_stats={
            "theoretical_IN_window_s":  f"[{th_in_s:.2f}, {th_in_e:.2f}]",
            "theoretical_OUT_window_s": f"[{th_out_s:.2f}, {th_out_e:.2f}]",
            "n_per40_in_cohort":        n_per40,
            "n_per240_in_cohort":       n_per240,
        },
    )

    pu.write_figure_stub(_meta_stub, plot_type="hg_per40_window_fitness",
                         subfig_filenames=[figure_name])
    print(f"   stub    → output/TEXFIGU/{figure_name}.tex")


# ── Loop over all four thesis frequencies ───────────────────────────────
for _f in TARGET_FREQS:
    build_figure_for(_f)
