"""
A_IN and A_OUT (FFT amplitude) vs wavenumber k — 3 subfigures (A1/A2/A3).

Data read from output/TABLES/data/ch05_in_out_amplitudes_vs_freq_table.csv
(generated by analysis_scratch/in_out_amplitudes_table.py).

Per-side σ(A_IN) and σ(A_OUT) come straight from the table — shown here
as errorbars. Includes A3 @ 1.6 Hz (the only cell flagged as
dropout-prone in field log; σ(A_IN) at A3/1.6/uten = 1.02 mm is the
largest in the table, ~5 %, otherwise scatter is small).

Conventions:
  - Main x-axis : k [rad/m] (linear)
  - Top x-axis  : f [Hz], ticks at the four canon frequencies
  - Color       : red = full wind, blue = no wind (WIND_COLOR_MAP)
  - Marker      : ○ A1, □ A2, △ A3 (one per subfigure)
  - Style       : solid + filled = A_IN; dashed + hollow = A_OUT
  - Corner label: $A_{FFT}$ via apply_horizontal_ylabel (leftmost panel)
"""

import sys
from pathlib import Path

import matplotlib
import numpy as np
import pandas as pd

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.lines as mlines

BASE = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE))

from wavescripts.plot_utils import (
    apply_thesis_style,
    apply_horizontal_ylabel,
    add_freq_axis,
    freq_to_k,
    WIND_COLOR_MAP,
)

apply_thesis_style()


CSV = BASE / "output" / "TABLES" / "data" / "ch05_in_out_amplitudes_vs_freq_table.csv"
df = pd.read_csv(CSV)

AMP_LABELS = {0.10: "A1", 0.20: "A2", 0.30: "A3"}
MARKER = {"A1": "o", "A2": "s", "A3": "^"}
AMP_TITLE = {"A1": r"$A_1$ (0.10 V)",
             "A2": r"$A_2$ (0.20 V)",
             "A3": r"$A_3$ (0.30 V)"}
WIND_LABEL = {"no": "uten vind", "full": "full vind"}


fig, axes = plt.subplots(1, 3, figsize=(9.5, 3.8), sharey=False)

for ax, amp_v in zip(axes, [0.10, 0.20, 0.30]):
    amp = AMP_LABELS[amp_v]
    mark = MARKER[amp]
    sub_amp = df[np.isclose(df["amp_v"], amp_v)]
    for wind in ["no", "full"]:
        sub = sub_amp[sub_amp["wind"] == wind].sort_values("freq")
        k = freq_to_k(sub["freq"].to_numpy())
        color = WIND_COLOR_MAP[wind]

        ax.errorbar(k, sub["A_in"], yerr=sub["A_in_sd"],
                    color=color, marker=mark, linestyle="-",
                    linewidth=1.1, markersize=5.5, capsize=2)
        ax.errorbar(k, sub["A_out"], yerr=sub["A_out_sd"],
                    color=color, marker=mark, linestyle="--",
                    linewidth=1.1, markersize=5.5, capsize=2,
                    markerfacecolor="white", markeredgecolor=color)

    ax.set_title(AMP_TITLE[amp], pad=22)
    ax.set_xlabel("")
    ax.grid(True, alpha=0.3)

    secax = add_freq_axis(ax, label="")
    secax.set_xticks([1.3, 1.4, 1.5, 1.6])
    secax.set_xticklabels(["1.3", "1.4", "1.5", "1.6"])
    secax.set_xlabel("")

# Layout: legend lives inside the middle panel, so use the full width.
fig.subplots_adjust(left=0.07, right=0.98, top=0.78, bottom=0.13,
                    wspace=0.28)
fig.canvas.draw()

# Single-letter axis identifiers k / f at the right edge of each panel.
for ax in axes:
    p = ax.get_position()
    fig.text(p.x1, p.y0 - 0.04, r"$k$", ha="right", va="top", fontsize=11)
    fig.text(p.x1, p.y1 + 0.02, r"$f$", ha="right", va="bottom", fontsize=11)

apply_horizontal_ylabel(axes[0], r"$A_{\mathrm{FFT}}$ [mm]",
                        fontsize=12, y_offset_pad=0.13)

wind_handles = [
    mlines.Line2D([], [], color=WIND_COLOR_MAP[w], marker="o",
                  linestyle="-", markersize=6, label=WIND_LABEL[w])
    for w in ["no", "full"]
]
inout_handles = [
    mlines.Line2D([], [], color="gray", marker="o", linestyle="-",
                  markersize=6, label=r"$A_\mathrm{IN}$"),
    mlines.Line2D([], [], color="gray", marker="o", linestyle="--",
                  markersize=6, markerfacecolor="white",
                  markeredgecolor="gray", label=r"$A_\mathrm{OUT}$"),
]
axes[1].legend(handles=wind_handles + inout_handles,
               loc="lower center", ncol=2, frameon=True,
               handlelength=2.0, fontsize=9,
               framealpha=0.9, edgecolor="gray")

OUT = Path(__file__).parent / "in_out_amplitudes_vs_freq.pdf"
fig.savefig(OUT)
print(f"saved → {OUT}")
